#!/usr/bin/env python3
"""
plot_density_3d.py — Interactive 3-D scatter plot of both density species.

Both species are drawn in a single gnuplot 3-D window (x, y, ρ).
The window stays open and responds to mouse rotation, zoom, and zoom-to-fit.

Usage
-----
  python3 scripts/plot_density_3d.py output/
        → plots density_species{1,2}_final.dat

  python3 scripts/plot_density_3d.py output/density_species1_iter_001000.dat \\
                                      output/density_species2_iter_001000.dat
        → plots an arbitrary pair of files

  python3 scripts/plot_density_3d.py output/density_species1_final.dat
        → plots a single file (one species)

Requirements
------------
  gnuplot >= 5.2 with the 'qt' or 'wxt' terminal built in.
  The terminal is detected automatically; set GNUPLOT_TERM=wxt (or qt/x11)
  to override.
"""

import os
import sys
import subprocess
import shutil
import tempfile

# ── Terminal preference ────────────────────────────────────────────────────────

# Interactive terminals in preference order.
# 'qt'  — Qt5-based, best mouse support, requires gnuplot-qt
# 'wxt' — wxWidgets, widely available
# 'x11' — Xlib, works everywhere but basic interactivity
_PREFERRED_TERMS = ["qt", "wxt", "x11"]


def _detect_terminal() -> str:
    """Return the first interactive gnuplot terminal available.

    Each candidate is probed by asking gnuplot to switch to it and then quit.
    A 2-second timeout prevents any single probe from hanging.
    """
    override = os.environ.get("GNUPLOT_TERM", "").strip()
    if override:
        return override

    for t in _PREFERRED_TERMS:
        try:
            r = subprocess.run(
                ["gnuplot", "-e", f"set terminal {t}; quit"],
                capture_output=True, text=True, timeout=2
            )
            if r.returncode == 0:
                return t
        except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
            pass

    return _PREFERRED_TERMS[0]   # last-resort fallback


# ── File helpers ───────────────────────────────────────────────────────────────

def _find_final_pair(output_dir: str):
    """Return (path1, path2) for the final density files in output_dir."""
    data_dir = os.path.join(output_dir, "data")
    p1 = os.path.join(data_dir, "density_species1_final.dat")
    p2 = os.path.join(data_dir, "density_species2_final.dat")
    missing = [p for p in (p1, p2) if not os.path.exists(p)]
    if missing:
        sys.exit(f"Error: file(s) not found:\n  " + "\n  ".join(missing))
    return p1, p2


def _rho_range(*paths):
    """Return (rho_min, rho_max) over all data files (column 3)."""
    lo, hi = float("inf"), float("-inf")
    for p in paths:
        with open(p) as fh:
            for line in fh:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    v = float(parts[2])
                    if v < lo:
                        lo = v
                    if v > hi:
                        hi = v
                except ValueError:
                    pass
    return lo, hi


# ── gnuplot script builder ─────────────────────────────────────────────────────

# Colour palette: blue-family for species 1, red-family for species 2.
_COLOUR1 = "#2171b5"   # medium blue
_COLOUR2 = "#cb181d"   # brick red

_PT_SOLID  = 7    # filled circle
_PS        = 0.50 # point size


def _build_script(files: list[tuple[str, str]], terminal: str,
                  zmin: float, zmax: float) -> str:
    """
    Build a gnuplot script for an interactive 3-D scatter plot.

    files : list of (dat_path, species_label) pairs
    """
    splot_parts = []
    colours = [_COLOUR1, _COLOUR2, "#2ca25f", "#756bb1"]

    for idx, (path, label) in enumerate(files):
        colour = colours[idx % len(colours)]
        splot_parts.append(
            f"    '{path}' using 1:2:3 with points "
            f"pt {_PT_SOLID} ps {_PS} lc rgb '{colour}' title '{label}'"
        )

    splot_cmd = "splot \\\n" + ", \\\n".join(splot_parts)

    title_str = " & ".join(label for _, label in files)

    script = f"""\
# ── Interactive 3-D density scatter plot ─────────────────────────────────────
# Generated by plot_density_3d.py
# Mouse controls (qt/wxt): left-drag to rotate, scroll to zoom, 'u' to unzoom,
#   'r' to reset, 'a' to autoscale, button-3 for context menu.

set terminal {terminal} size 1000,800 title "SALR DFT — 3D density"

set title "{title_str}\\n{{/:Italic=11 drag to rotate · scroll to zoom · 'q' to quit}}"
set xlabel "x" offset 0,-1
set ylabel "y" offset 0,-1
set zlabel "{{/Symbol r}}(x,y)" rotate by 90

set zrange [{zmin:.6g}:{zmax:.6g}]
set ticslevel 0          # origin of z-axis at the plot floor
set grid ztics

set key outside right top spacing 1.4

# Colour the points by z value as well (optional: makes depth cues visible)
# set pm3d depthorder base

{splot_cmd}

pause mouse close "\\nClose the window (or press 'q') to exit.\\n"
"""
    return script


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    arg1 = sys.argv[1]

    # -- resolve file pair -------------------------------------------------------
    if os.path.isdir(arg1):
        path1, path2 = _find_final_pair(arg1)
        files = [(path1, "Species 1"), (path2, "Species 2")]

    elif len(sys.argv) >= 3 and os.path.isfile(sys.argv[2]):
        # Two explicit files
        files = [(sys.argv[1], "Species 1"), (sys.argv[2], "Species 2")]
        for p, _ in files:
            if not os.path.exists(p):
                sys.exit(f"Error: file not found: {p}")

    elif os.path.isfile(arg1):
        files = [(arg1, os.path.basename(arg1))]

    else:
        sys.exit(f"Error: '{arg1}' is neither a directory nor a file.")

    # -- sanity-check gnuplot ---------------------------------------------------
    if shutil.which("gnuplot") is None:
        sys.exit("Error: 'gnuplot' not found on PATH.")

    # -- detect terminal --------------------------------------------------------
    term = _detect_terminal()
    print(f"Using gnuplot terminal: {term}")

    # -- z range over all files -------------------------------------------------
    zmin, zmax = _rho_range(*(p for p, _ in files))

    # -- build and run gnuplot script -------------------------------------------
    script = _build_script(files, term, zmin, zmax)

    tmp = tempfile.NamedTemporaryFile(suffix=".gp", mode="w",
                                     delete=False, prefix="salr_3d_")
    tmp.write(script)
    tmp.close()

    print("Launching interactive gnuplot window …")
    print("  Mouse: left-drag → rotate | scroll → zoom | 'q' → quit")
    for p, label in files:
        print(f"  {label}: {p}")

    try:
        subprocess.run(["gnuplot", tmp.name])
    finally:
        os.unlink(tmp.name)


if __name__ == "__main__":
    main()
